name: shell Commands
on:
  push:
    branches:
        - master

jobs:
   deploy:
    name: deployment
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: [3.8]
        node-version: ['12.x']
        appname: ['cakephpapp']
        deploy-group: ['staging']
        s3-filename: ['staging-cakephpapp-${{ github.sha }}']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install php
        run: |
          php -v
      - name: Install AWS Client
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
      - name: install composer
        run: |
          curl -sS https://getcomposer.org/installer | php
          sudo mv composer.phar /usr/local/bin/composer
          sudo chmod +x /usr/local/bin/composer

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AES_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Deploy push to AWS S3
      - name: AWS Deploy push
        run: |
          aws deploy push \
          --application-name ${{ matrix.appname }} \
          --description "This is a revision for the ${{ matrix.appname }}-${{ github.sha }}" \
          --ignore-hidden-files \
          --s3-location s3://${{secrets.S3_BUCKET_NAME}}/${{ matrix.s3-filename }}.zip \
          --source .

      # Create deployment to CodeDeploy
      - name: AWS Create Deployment
        run: |
          aws deploy create-deployment \
           --application-name ${{ matrix.appname }} \
           --deployment-config-name CodeDeployDefault.OneAtATime \
           --deployment-group-name ${{ matrix.deploy-group }} \
           --file-exists-behavior OVERWRITE \
           --ignore-application-stop-failures \
           --s3-location bucket=${{ secrets.S3_BUCKET_NAME }},key=${{ matrix.s3-filename }}.zip,bundleType=zip \
