name: shell Commands
on:
  push:
    branches:
        - master

jobs:
   deploy:
    name: deployment
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: install php
        run: |
          sudo apt-get install curl
          sudo apt-get install -y php7.2

          php -v
